services:
  local-db:
    image: postgres:15.5-alpine
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_DB=students
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
    ports:
      - '5432:5432'
